### ISSUE TITLE
Problema com o campo {"response": "true"} no json.

### ISSUE THREAD

**Issue by ivmelo** [Filmap/filmap_api#15]
Whe the api returns the movie list, it also returns an response:true json object. The problem is that the response is at the wrong place within the json code and the windows phone api mistakes it for a movie when deserializing the json code. The result is that an empty movie is included in the My Movies List.

Example: 
GET http://apifilmap.ivanilson.xyz/films

Will return:
[
{
"id": "41",
"omdb": "tt0796368",
"user_id": "8",
"watched": "1",
"created_at": "2015-12-07 23:44:22",
"updated_at": "2015-12-07 23:44:22"
},
{
"id": "40",
"omdb": "tt0796366",
"user_id": "8",
"watched": "1",
"created_at": "2015-12-07 23:44:22",
"updated_at": "2015-12-07 23:44:22"
},
{
"Response": true
}
]

The quickest fix for this is just to remove the "response" field from the json response. I can still use the http status code to find out if the response was successful or not.

**Comment by duartefq** [comment]
Yeah its fine i will fix it later, hold on a sec
