### ISSUE TITLE
films/omdbid/watch retorna 500 Internal Server Error

### ISSUE THREAD

**Issue by ivmelo** [Filmap/filmap_api#21]
O filme e atualizado, mas retorna erro quando em producao.

**Comment by duartefq** [comment]
Lembrando que eh /films/omdbid/watch, e não watched. Eh como se estivesse dizendo "assistir

Sent from my BlackBerry 10 smartphone.
From: Ivanilson Melo
Sent: Tuesday, December 8, 2015 14:26
To: duartefq/filmap_api
Reply To: duartefq/filmap_api
Subject: [filmap_api] films/omdbid/watched retorna 500 Internal Server Error (#21)

O filme e atualizado, mas retorna erro quando em producao.

---

Reply to this email directly or view it on GitHub:
https://github.com/duartefq/filmap_api/issues/21
