### ISSUE TITLE
500 Internal Server Error ao cadastrar user

### ISSUE THREAD

**Issue by duartefq** [Filmap/filmap_api#9]
Assim como #8, user é cadastrado mas server retorna 500.

**Comment by ivmelo** [comment]
Acho que era um erro no servidor (Apache), depois que eu mudei as permissoes das pastas storage e vendor pra 755 ele esta retornando 200 OK.

**Comment by duartefq** [comment]
ah certo. Legal! Mas aproveitei e coloquei pra retornar um `{"response": True}` ao realizar os cadastros. Pode vir a calhar algum dia :grin:

**Comment by ivmelo** [comment]
Otimo. <--- Sem acento pq tou no windows. huehue
